### ISSUE TITLE
EMail 인증 기능 포함시키기

### ISSUE THREAD

**Issue by ingyocode** [Picnic-GSM/GOOUT_SERVER#15]
EMail이 인증되어야 로그인이 되는 방식으로 개발할 예정

**Comment by icefirebear** [comment]
이메일 인증 기능 구현 시에는 Redis를 사용해서 구현하고 `util`디렉토리에 모듈 클래스 만들어서 사용하는 방식이 좋을 것 같습니다.
참고용으로 [python redis module boilerplate](https://github.com/icefirebear/python-redis-boilerplate/blob/main/main.py) Python으로 개발한 모듈 boilerplate 올려두겠습니다.
